#!/usr/bin/env python
import pygame as pg
import cv2
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np

pg.init()
clock = pg.time.Clock()

screen = pg.display.set_mode((768,512))

bgnd = pg.Surface(screen.get_size())
for x in range(256):
  for y in range(256):
    bgnd.set_at((x,y),(x,0,y))#primeiro
for x in range(256,512):
  for y in range(256):
    bgnd.set_at((x,y),(0,x%256,y))#segundo
for x in range(256):
  for y in range(256,512):
    bgnd.set_at((x,y),(x,y%256,0))#quarto
for x in range(256,512):
  for y in range(256,512):
    bgnd.set_at((x,y),(x%256,y%256,y%256))#quinto
for x in range(512,768):
  for y in range(256):
    bgnd.set_at((x,y),(y%256,x%256,y%256))#terceiro
for x in range(512,768):
  for y in range(256,512):
    bgnd.set_at((x,y),(y%256,y%256,x%256))#sexto
bgnd = bgnd.convert()

screen.blit(bgnd,(0,0))
pg.display.flip()
array = pg.surfarray.array3d(screen)

transformed = np.zeros((array.shape[1],array.shape[0],3),dtype=np.int16)
for i in range(array.shape[1]):
  transformed[i]=array[:,i,:]

print(transformed.shape)
print(array.shape)
#plt.plot(array)
#plt.show()

print(transformed[125,125])
plt.imshow(transformed)
plt.show()

mainloop = True
while mainloop:
  for event in pg.event.get():
    if event.type == pg.QUIT:
      mainloop = False
    if event.type == pg.KEYDOWN:
      if event.key == pg.K_i:
        print('i')

