#!/usr/bin/env python
import pygame as pg

pg.init()
#clock = 

screen = pg.display.set_mode((640,480))

bgnd = pg.Surface(screen.get_size())
ncol = 25
colstep = 255//ncol
for x in range(640):
  nx = x//(640//ncol)
  for y in range(480):
    bgnd.set_at((x,y),(255-y%255,0,nx*colstep))
bgnd = bgnd.convert()

mainloop = True
while mainloop:
  for event in pg.event.get():
    if event.type == pg.QUIT:
      mainloop = False
    if event.type == pg.KEYDOWN:
      if event.key == pg.K_i:
        print('i')
  
  screen.blit(bgnd,(0,0))
  pg.display.flip()
