#!/usr/bin/env python
import pygame as pg

pg.init()
screen = pg.display.set_mode((640,480))
bgnd = pg.Surface(screen.get_size())
bgnd.fill((20,160,20))
bgnd = bgnd.convert()

clock = pg.time.Clock()
poins = []
curcir = pg.mouse.get_pos()
scroll = 0;

mainloop = True
while mainloop:
  screen.blit(bgnd,(0,0))
  pg.draw.circle(screen,(160,160,20),(640//2,480//2),25)

  for event in pg.event.get():
    if event.type == pg.QUIT:
      mainloop = False
    elif event.type == pg.MOUSEMOTION:
      curcir = event.pos
      if event.buttons[0] == 1:
        poins.append(event.pos)
    elif event.type == pg.MOUSEBUTTONDOWN:
      poins.append(event.pos)
    elif event.type == pg.KEYDOWN:
      if event.key == pg.K_DOWN:
        scroll +=1
      elif event.key == pg.K_UP:
        scroll -=1
    #print(event)

  pg.draw.circle(screen,(160,160,20),curcir,25)
  for i,p in enumerate(poins):
    poins[i]=(p[0],p[1]+scroll)
    pg.draw.circle(screen,(160,160,20),p,25)
  pg.display.flip()
  clock.tick(60)

pg.quit()
