#!/usr/bin/env python

import pygame as pg

pg.init()
screen = pg.display.set_mode((640,480))
bgnd = pg.Surface(screen.get_size())
bgnd.fill((20,160,20))
bgnd = bgnd.convert()
screen.blit(bgnd,(0,0))

clock = pg.time.Clock()
poins = []

mainloop = True
while mainloop:
  screen.blit(bgnd,(0,0))
  pg.draw.circle(screen,(160,160,20),(640//2,480//2),25)

  for event in pg.event.get():
    if event.type == pg.QUIT:
      mainloop = False
    if event.type == pg.MOUSEMOTION:
      pg.draw.circle(screen,(160,160,20),event.pos,25)
      print(event)
    if event.type == pg.MOUSEBUTTONDOWN:
      poins.append(event.pos)
      
  for p in poins:
    pg.draw.circle(screen,(160,160,20),p,25)
  pg.display.flip()
  clock.tick(60)

pg.quit()
