#!/usr/bin/env python

import pygame as pg

pg.init()
screen = pg.display.set_mode((640,480))
background = pg.Surface(screen.get_size())
background.fill((255,255,255))
background = background.convert()

clock = pg.time.Clock()

mainloop = True
FPS = 60
playtime = 0.0

font = pg.font.SysFont('mono',20,bold=True)

def draw_text(text):
  fw, fh = font.size(text)
  surface = font.render(text,True,(0,255,0))
  screen.blit(surface,((640-fw)//2,(480-fh)//2))

ballsurface = pg.Surface((50,50))
pg.draw.circle(ballsurface,(0,0,255),(25,25),25)
pg.draw.rect(background,(255,0,0),(0,0,100,100))

pox = 0
poy = 0

while mainloop:
  milliseconds = clock.tick(FPS)
  playtime += milliseconds / 1000.0

  for event in pg.event.get():
    if event.type == pg.QUIT:
      mainloop = False
    elif event.type == pg.KEYDOWN:
      if event.key == pg.K_ESCAPE:
        mainloop = False
    elif event.type == pg.MOUSEBUTTONDOWN:
      pox,poy = event.pos

  text = "FPS: %f2. Playtime = %f2."%(clock.get_fps(),playtime)
  pg.display.set_caption(text)
  screen.blit(background,(0,0))
  screen.blit(ballsurface,(pox,poy))
  draw_text(text)
  pg.display.flip()

pg.quit()
print("This game was played for {0:.2f} seconds".format(playtime))
