#!/usr/bin/env python
import numpy as np
import pyscreenshot as ss
import cv2 as cv

img = ss.grab()
array = np.array(img)
array = cv.cvtColor(array,cv.COLOR_RGB2BGR)
fourcc = cv.VideoWriter_fourcc(*'XVID')
out = cv.VideoWriter('output.avi',fourcc, 6, array.shape[:2])

n = 0
while n < 6:
  out.write(array)
  img = ss.grab()
  array = np.array(img)
  array = cv.cvtColor(array,cv.COLOR_RGB2BGR)
  n += 1

out.release()
